# Generated by Django 2.0.2 on 2018-02-23 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=20)),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('describe', models.TextField()),
            ],
            options={
                'ordering': ('-post_date',),
            },
        ),
    ]
