# Generated by Django 2.0.2 on 2018-02-24 13:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_say'),
    ]

    operations = [
        migrations.CreateModel(
            name='Riji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('img', models.ImageField(upload_to='img')),
            ],
            options={
                'ordering': ('-post_date',),
            },
        ),
    ]
