# Generated by Django 2.0.2 on 2018-02-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_riji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riji',
            name='img',
            field=models.ImageField(default='image/default.png', upload_to='image/%Y/%m', verbose_name='头像'),
        ),
    ]
