# Generated by Django 2.0.2 on 2018-02-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_auto_20180224_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riji',
            name='img',
            field=models.ImageField(default='image/default.png', upload_to='image', verbose_name='头像'),
        ),
    ]
