# Generated by Django 2.0.2 on 2018-02-25 04:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_auto_20180224_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='img/default.png', upload_to='img', verbose_name='相册')),
                ('miaoshu', models.TextField()),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-post_date',),
            },
        ),
    ]
