# Generated by Django 2.0.2 on 2018-02-25 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_xc'),
    ]

    operations = [
        migrations.AddField(
            model_name='xc',
            name='height',
            field=models.IntegerField(default=200),
        ),
    ]
