# Generated by Django 2.0.2 on 2018-02-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0007_xc_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='artical',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
